[package]
name = "rust-gui-toolkit-study"
version = "0.1.0"
authors = ["TesX <tesfabpel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambassador = "0.2.1"
